services:
  sensor-web-services:
    build: .
    container_name: sensor-web-services
    ports:
      - "32000:32000"
      - "3301:3301"
    volumes:
      - /mnt/sensor-web-services/:/app/configs/
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:32000/ready" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
